$(info ************************************************************************)
$(info ***  make libtextutils                                               ***)
$(info ************************************************************************)
# -----------------------------------------------------------------------------
# IBM Streams Compiler/Linker Options
# -----------------------------------------------------------------------------

SPL_PKGCFG=$(STREAMS_INSTALL)/bin/dst-pe-pkg-config.sh
SPL_PKG=dst-spl-pe-install
SPL_COMPILE_OPTIONS = `$(SPL_PKGCFG) --cflags $(SPL_PKG)`
SPL_LINK_OPTIONS = `$(SPL_PKGCFG) --libs $(SPL_PKG)`

# -----------------------------------------------------------------------------
# phony targets are targets being not in the filesystem but are always "active"
# -----------------------------------------------------------------------------

.PHONY: all build clean clean_objects clean_library $(LIB) $(OBJ)

# -----------------------------------------------------------------------------
# Folders
# -----------------------------------------------------------------------------

INC := ../include/libtextutils
LIB := ../lib
OBJ := libtextutils/obj
SRC := libtextutils

# -----------------------------------------------------------------------------
# Library
# -----------------------------------------------------------------------------

LIBRARY := $(LIB)/libstreamsx-tk-text-utils.so

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------

INCLUDES = $(wildcard $(INC)/*.h) $(wildcard $(SRC)/*.h) 
SOURCES  = $(wildcard $(SRC)/*.cpp)
OBJECTS  = $(patsubst $(SRC)/%.cpp,$(OBJ)/%.o,$(SOURCES))
LINKFLAGS := -shared $(SPL_LINK_OPTIONS)
include ./makefiles/Makefile.options
CXXFLAGS += -O3 -fPIC -I $(SRC) -I $(INC) $(SPL_COMPILE_OPTIONS)

deliver: all

all: clean build clean_up

build: $(LIBRARY)

$(LIB) $(OBJ):
	@mkdir -pv $@
	
$(OBJ)/%.o: $(SRC)/%.cpp $(INCLUDES)
	@echo Compiling '$<' ...
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(LIBRARY): $(LIB) $(OBJ) $(OBJECTS)
	@echo Building C++ shared library '$@'
	$(CXX) $(LINKFLAGS) -o $@  $(OBJECTS)

clean: clean_objects clean_library

clean_objects:
	@echo Cleaning object files ...
	@rm -rfv $(OBJ)

clean_up: clean_objects
	@echo Cleaning object files ...
	@rm -rfv $(OBJ)

clean_library:
	@echo Cleaning library files ...
	@rm -fv $(LIBRARY)

